# Generated by Django 5.1.3 on 2024-12-13 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flyer',
            name='qrpath',
            field=models.ImageField(blank=True, null=True, upload_to='media/qr-flyer/'),
        ),
        migrations.AddField(
            model_name='identity',
            name='qrpath',
            field=models.ImageField(blank=True, null=True, upload_to='media/qr-identity/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='media/qr-contact/'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('user', 'email')},
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['user'], name='client_cont_user_id_1e671d_idx'),
        ),
    ]
