# Generated by Django 5.1.3 on 2024-12-14 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_flyer_qrpath_identity_qrpath_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flyer',
            old_name='company',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='company',
        ),
    ]
