# Generated by Django 5.1.3 on 2024-12-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_rename_number_identity_id_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='validity_time',
            new_name='expiry_date',
        ),
    ]
